import type { ModelInsert } from '@/types/database'

export const seedModels: ModelInsert[] = [
  // ============================================================
  // LLMs
  // ============================================================
  {
    name: 'GPT-4o',
    slug: 'gpt-4o',
    maker: 'OpenAI',
    category: 'llm',
    description:
      'OpenAI\'s flagship multimodal model, handling text, vision, and audio in a single network. Replaced GPT-4 Turbo as the default ChatGPT model and is roughly half its price.',
    current_version: 'gpt-4o-2024-08-06',
    pricing_input_per_1m: 2.5,
    pricing_output_per_1m: 10,
    context_window: 128000,
    release_date: '2024-05-13',
  },
  {
    name: 'GPT-4o mini',
    slug: 'gpt-4o-mini',
    maker: 'OpenAI',
    category: 'llm',
    description:
      'A small, fast, and cheap model that replaced GPT-3.5 Turbo. Multimodal on input and priced aggressively for high-volume workloads.',
    current_version: 'gpt-4o-mini-2024-07-18',
    pricing_input_per_1m: 0.15,
    pricing_output_per_1m: 0.6,
    context_window: 128000,
    release_date: '2024-07-18',
  },
  {
    name: 'GPT-4 Turbo',
    slug: 'gpt-4-turbo',
    maker: 'OpenAI',
    category: 'llm',
    description:
      'The 2024 refresh of GPT-4 with a 128K context window and improved instruction following. Superseded by GPT-4o for most use cases but still available via the API.',
    current_version: 'gpt-4-turbo-2024-04-09',
    pricing_input_per_1m: 10,
    pricing_output_per_1m: 30,
    context_window: 128000,
    release_date: '2024-04-09',
  },
  {
    name: 'o3',
    slug: 'o3',
    maker: 'OpenAI',
    category: 'llm',
    description:
      'OpenAI\'s flagship reasoning model that thinks step-by-step before answering. Strong on math, science, and coding benchmarks at the cost of higher latency.',
    current_version: 'o3-2025-04-16',
    pricing_input_per_1m: 2,
    pricing_output_per_1m: 8,
    context_window: 200000,
    release_date: '2025-04-16',
  },
  {
    name: 'o4-mini',
    slug: 'o4-mini',
    maker: 'OpenAI',
    category: 'llm',
    description:
      'A smaller, cheaper reasoning model in the o-series lineup with competitive performance for its price. Supports tool use and vision inputs during reasoning.',
    current_version: 'o4-mini-2025-04-16',
    pricing_input_per_1m: 1.1,
    pricing_output_per_1m: 4.4,
    context_window: 200000,
    release_date: '2025-04-16',
  },
  {
    name: 'Claude Opus 4',
    slug: 'claude-opus-4',
    maker: 'Anthropic',
    category: 'llm',
    description:
      'Anthropic\'s most capable model, tuned for long-horizon agentic coding and complex reasoning. Introduced extended thinking and tool use during reasoning.',
    current_version: 'claude-opus-4-20250514',
    pricing_input_per_1m: 15,
    pricing_output_per_1m: 75,
    context_window: 200000,
    release_date: '2025-05-22',
  },
  {
    name: 'Claude Sonnet 4',
    slug: 'claude-sonnet-4',
    maker: 'Anthropic',
    category: 'llm',
    description:
      'Mid-tier Claude 4 model balancing cost and capability, widely used as a coding default. Supports a 1M-token context window in beta.',
    current_version: 'claude-sonnet-4-20250514',
    pricing_input_per_1m: 3,
    pricing_output_per_1m: 15,
    context_window: 200000,
    release_date: '2025-05-22',
  },
  {
    name: 'Claude Haiku 3.5',
    slug: 'claude-haiku-3-5',
    maker: 'Anthropic',
    category: 'llm',
    description:
      'A small, fast Claude model intended for high-volume low-latency tasks. Notably matches the old Claude 3 Opus on many benchmarks at a fraction of the cost.',
    current_version: 'claude-3-5-haiku-20241022',
    pricing_input_per_1m: 0.8,
    pricing_output_per_1m: 4,
    context_window: 200000,
    release_date: '2024-10-22',
  },
  {
    name: 'Gemini 2.5 Pro',
    slug: 'gemini-2-5-pro',
    maker: 'Google DeepMind',
    category: 'llm',
    description:
      'Google\'s flagship reasoning model with a 2M-token context window. Strong on long-context retrieval, coding, and multimodal understanding.',
    current_version: 'gemini-2.5-pro',
    pricing_input_per_1m: 1.25,
    pricing_output_per_1m: 10,
    context_window: 2000000,
    release_date: '2025-03-25',
  },
  {
    name: 'Gemini 2.5 Flash',
    slug: 'gemini-2-5-flash',
    maker: 'Google DeepMind',
    category: 'llm',
    description:
      'Faster, cheaper sibling of 2.5 Pro with optional "thinking" mode. Aimed at high-throughput apps that still need multimodal support.',
    current_version: 'gemini-2.5-flash',
    pricing_input_per_1m: 0.3,
    pricing_output_per_1m: 2.5,
    context_window: 1000000,
    release_date: '2025-04-09',
  },
  {
    name: 'Gemini 2.0 Flash',
    slug: 'gemini-2-0-flash',
    maker: 'Google DeepMind',
    category: 'llm',
    description:
      'The first generally-available 2.0 model, emphasizing speed and native tool use. Includes experimental image and audio generation modes.',
    current_version: 'gemini-2.0-flash',
    pricing_input_per_1m: 0.1,
    pricing_output_per_1m: 0.4,
    context_window: 1000000,
    release_date: '2025-02-05',
  },
  {
    name: 'Llama 4 Scout',
    slug: 'llama-4-scout',
    maker: 'Meta',
    category: 'llm',
    description:
      'Open-weight mixture-of-experts model with a 10M-token context window and 17B active parameters. Designed to fit on a single H100 with efficient long-context inference.',
    current_version: 'llama-4-scout-17b-16e',
    pricing_input_per_1m: 0,
    pricing_output_per_1m: 0,
    context_window: 10000000,
    release_date: '2025-04-05',
  },
  {
    name: 'Llama 4 Maverick',
    slug: 'llama-4-maverick',
    maker: 'Meta',
    category: 'llm',
    description:
      'Larger open-weight MoE sibling of Scout with 17B active parameters across 128 experts. Positioned as a GPT-4o-class chat and coding model.',
    current_version: 'llama-4-maverick-17b-128e',
    pricing_input_per_1m: 0,
    pricing_output_per_1m: 0,
    context_window: 1000000,
    release_date: '2025-04-05',
  },
  {
    name: 'Llama 3.3 70B',
    slug: 'llama-3-3-70b',
    maker: 'Meta',
    category: 'llm',
    description:
      'Open-weight 70B dense model that closed much of the gap to Llama 3.1 405B on instruction following. Popular as a self-hosted alternative to frontier APIs.',
    current_version: 'llama-3.3-70b-instruct',
    pricing_input_per_1m: 0,
    pricing_output_per_1m: 0,
    context_window: 128000,
    release_date: '2024-12-06',
  },
  {
    name: 'Mistral Large',
    slug: 'mistral-large',
    maker: 'Mistral AI',
    category: 'llm',
    description:
      'Mistral\'s flagship closed-weight model, optimized for reasoning and code. The 2 release improved multilingual performance and function calling.',
    current_version: 'mistral-large-2411',
    pricing_input_per_1m: 2,
    pricing_output_per_1m: 6,
    context_window: 128000,
    release_date: '2024-11-18',
  },
  {
    name: 'Mixtral 8x22B',
    slug: 'mixtral-8x22b',
    maker: 'Mistral AI',
    category: 'llm',
    description:
      'Open-weight sparse mixture-of-experts with 141B total and 39B active parameters. A strong open baseline for reasoning and multilingual tasks.',
    current_version: 'mixtral-8x22b-instruct-v0.1',
    pricing_input_per_1m: 2,
    pricing_output_per_1m: 6,
    context_window: 65536,
    release_date: '2024-04-17',
  },
  {
    name: 'Command R+',
    slug: 'command-r-plus',
    maker: 'Cohere',
    category: 'llm',
    description:
      'Cohere\'s enterprise model tuned for retrieval-augmented generation and tool use. The August refresh improved citations and JSON output reliability.',
    current_version: 'command-r-plus-08-2024',
    pricing_input_per_1m: 2.5,
    pricing_output_per_1m: 10,
    context_window: 128000,
    release_date: '2024-08-30',
  },
  {
    name: 'DeepSeek V3',
    slug: 'deepseek-v3',
    maker: 'DeepSeek',
    category: 'llm',
    description:
      '671B-parameter MoE open-weight model with 37B active parameters per token. Competitive with GPT-4o on many benchmarks at a small fraction of the cost.',
    current_version: 'deepseek-v3',
    pricing_input_per_1m: 0.27,
    pricing_output_per_1m: 1.1,
    context_window: 128000,
    release_date: '2024-12-26',
  },
  {
    name: 'DeepSeek R1',
    slug: 'deepseek-r1',
    maker: 'DeepSeek',
    category: 'llm',
    description:
      'Open-weight reasoning model trained with large-scale reinforcement learning. Offered at a fraction of o1\'s price and sparked broad interest in open reasoning.',
    current_version: 'deepseek-r1',
    pricing_input_per_1m: 0.55,
    pricing_output_per_1m: 2.19,
    context_window: 65536,
    release_date: '2025-01-20',
  },
  {
    name: 'Grok 3',
    slug: 'grok-3',
    maker: 'xAI',
    category: 'llm',
    description:
      'xAI\'s flagship model, trained on the Colossus supercluster. Adds a "Think" reasoning mode and real-time X-data grounding.',
    current_version: 'grok-3',
    pricing_input_per_1m: 3,
    pricing_output_per_1m: 15,
    context_window: 1000000,
    release_date: '2025-02-17',
  },
  {
    name: 'Grok 3 Mini',
    slug: 'grok-3-mini',
    maker: 'xAI',
    category: 'llm',
    description:
      'Smaller, faster Grok 3 variant aimed at low-latency conversational use. Retains reasoning mode for math and coding tasks.',
    current_version: 'grok-3-mini',
    pricing_input_per_1m: 0.3,
    pricing_output_per_1m: 0.5,
    context_window: 131072,
    release_date: '2025-02-17',
  },
  {
    name: 'Qwen 3 72B',
    slug: 'qwen-3-72b',
    maker: 'Alibaba',
    category: 'llm',
    description:
      'Open-weight dense model in the Qwen 3 family with strong multilingual and coding performance. Supports a hybrid reasoning mode toggled via the prompt.',
    current_version: 'qwen3-72b',
    pricing_input_per_1m: 0,
    pricing_output_per_1m: 0,
    context_window: 131072,
    release_date: '2025-04-29',
  },
  {
    name: 'Qwen 3 235B',
    slug: 'qwen-3-235b',
    maker: 'Alibaba',
    category: 'llm',
    description:
      'Flagship Qwen 3 mixture-of-experts model with 235B total and 22B active parameters. Competitive with DeepSeek R1 and proprietary frontier models on reasoning.',
    current_version: 'qwen3-235b-a22b',
    pricing_input_per_1m: 0,
    pricing_output_per_1m: 0,
    context_window: 131072,
    release_date: '2025-04-29',
  },

  // ============================================================
  // Image generation
  // ============================================================
  {
    name: 'DALL-E 3',
    slug: 'dall-e-3',
    maker: 'OpenAI',
    category: 'image',
    description:
      'Text-to-image model integrated into ChatGPT and the OpenAI API. Known for strong prompt adherence and accurate in-image text rendering.',
    current_version: 'dall-e-3',
    pricing_input_per_1m: 0,
    pricing_output_per_1m: 0,
    context_window: 0,
    release_date: '2023-10-03',
  },
  {
    name: 'Midjourney v7',
    slug: 'midjourney-v7',
    maker: 'Midjourney',
    category: 'image',
    description:
      'Midjourney\'s v7 model with personalization enabled by default and a Draft mode for fast iteration. Leads on aesthetic quality in user preference tests.',
    current_version: 'v7',
    pricing_input_per_1m: 0,
    pricing_output_per_1m: 0,
    context_window: 0,
    release_date: '2025-04-04',
  },
  {
    name: 'Stable Diffusion 3.5',
    slug: 'stable-diffusion-3-5',
    maker: 'Stability AI',
    category: 'image',
    description:
      'Open-weight release of the 3.5 family including Large, Large Turbo, and Medium variants. Distributable under a permissive community license for non-commercial and small-commercial use.',
    current_version: '3.5-large',
    pricing_input_per_1m: 0,
    pricing_output_per_1m: 0,
    context_window: 0,
    release_date: '2024-10-22',
  },
  {
    name: 'Flux 1.1 Pro',
    slug: 'flux-1-1-pro',
    maker: 'Black Forest Labs',
    category: 'image',
    description:
      'Hosted image model that topped image-arena leaderboards at launch. Includes an Ultra mode supporting 4MP output at competitive speeds.',
    current_version: 'flux-1.1-pro',
    pricing_input_per_1m: 0,
    pricing_output_per_1m: 0,
    context_window: 0,
    release_date: '2024-10-03',
  },
  {
    name: 'Ideogram 3',
    slug: 'ideogram-3',
    maker: 'Ideogram',
    category: 'image',
    description:
      'Image model specialized in photorealism and reliable in-image typography. Adds a Style References feature for consistent visual identity.',
    current_version: '3.0',
    pricing_input_per_1m: 0,
    pricing_output_per_1m: 0,
    context_window: 0,
    release_date: '2025-03-26',
  },
  {
    name: 'Imagen 4',
    slug: 'imagen-4',
    maker: 'Google DeepMind',
    category: 'image',
    description:
      'Google\'s latest text-to-image model with improved text rendering and detail. Available in Gemini, Vertex AI, and Whisk.',
    current_version: 'imagen-4',
    pricing_input_per_1m: 0,
    pricing_output_per_1m: 0,
    context_window: 0,
    release_date: '2025-05-20',
  },

  // ============================================================
  // Code
  // ============================================================
  {
    name: 'GitHub Copilot',
    slug: 'github-copilot',
    maker: 'GitHub',
    category: 'code',
    description:
      'IDE-integrated AI pair programmer backed by multiple frontier models. Now includes an agentic coding mode and Copilot Workspace for multi-file tasks.',
    current_version: 'copilot-2025',
    pricing_input_per_1m: 0,
    pricing_output_per_1m: 0,
    context_window: 0,
    release_date: '2022-06-21',
  },
  {
    name: 'Cursor',
    slug: 'cursor',
    maker: 'Anysphere',
    category: 'code',
    description:
      'AI-first code editor built on a VS Code fork with deep multi-model integration. Known for its Composer agent and Tab autocomplete model.',
    current_version: '0.45',
    pricing_input_per_1m: 0,
    pricing_output_per_1m: 0,
    context_window: 0,
    release_date: '2023-03-14',
  },
  {
    name: 'Codex',
    slug: 'codex',
    maker: 'OpenAI',
    category: 'code',
    description:
      'OpenAI\'s cloud-based software engineering agent that runs tasks in parallel sandboxes. Powered by codex-1, a variant of o3 fine-tuned for real-world codebases.',
    current_version: 'codex-1',
    pricing_input_per_1m: 0,
    pricing_output_per_1m: 0,
    context_window: 0,
    release_date: '2025-05-16',
  },
  {
    name: 'AlphaCode 2',
    slug: 'alphacode-2',
    maker: 'Google DeepMind',
    category: 'code',
    description:
      'Competitive-programming system built on Gemini that reached the 85th percentile on Codeforces. Research system, not a public product.',
    current_version: 'alphacode-2',
    pricing_input_per_1m: 0,
    pricing_output_per_1m: 0,
    context_window: 0,
    release_date: '2023-12-06',
  },

  // ============================================================
  // Audio
  // ============================================================
  {
    name: 'Whisper v3',
    slug: 'whisper-v3',
    maker: 'OpenAI',
    category: 'audio',
    description:
      'Open-weight multilingual speech-to-text model covering 99 languages. Large-v3 improved robustness and added a faster turbo variant in 2024.',
    current_version: 'large-v3-turbo',
    pricing_input_per_1m: 0,
    pricing_output_per_1m: 0,
    context_window: 0,
    release_date: '2023-11-06',
  },
  {
    name: 'ElevenLabs v3',
    slug: 'elevenlabs-v3',
    maker: 'ElevenLabs',
    category: 'audio',
    description:
      'Expressive text-to-speech model with inline audio tags for emotion, laughter, and whispers. Supports 70+ languages with high prosody control.',
    current_version: 'eleven-v3',
    pricing_input_per_1m: 0,
    pricing_output_per_1m: 0,
    context_window: 0,
    release_date: '2025-06-05',
  },
  {
    name: 'Suno v4',
    slug: 'suno-v4',
    maker: 'Suno',
    category: 'audio',
    description:
      'Text-to-music generator producing vocals, lyrics, and instrumentals. v4 introduced sharper audio, cleaner vocals, and a remaster feature for older tracks.',
    current_version: 'v4',
    pricing_input_per_1m: 0,
    pricing_output_per_1m: 0,
    context_window: 0,
    release_date: '2024-11-19',
  },
  {
    name: 'Udio',
    slug: 'udio',
    maker: 'Udio',
    category: 'audio',
    description:
      'Text-to-music service competing directly with Suno on vocal quality and songwriting. Focuses on high-fidelity 2-minute generations with extend and remix tools.',
    current_version: 'v1.5',
    pricing_input_per_1m: 0,
    pricing_output_per_1m: 0,
    context_window: 0,
    release_date: '2024-04-10',
  },

  // ============================================================
  // Multimodal
  // ============================================================
  {
    name: 'Gemini Ultra',
    slug: 'gemini-ultra',
    maker: 'Google DeepMind',
    category: 'multimodal',
    description:
      'The original flagship 1.0 Gemini model, natively multimodal across text, images, audio, and video. Largely superseded by the Gemini 1.5 and 2.x lines.',
    current_version: '1.0-ultra',
    pricing_input_per_1m: 0,
    pricing_output_per_1m: 0,
    context_window: 32768,
    release_date: '2023-12-06',
  },
  {
    name: 'GPT-4V',
    slug: 'gpt-4v',
    maker: 'OpenAI',
    category: 'multimodal',
    description:
      'Vision-enabled GPT-4 variant that accepts images as part of the prompt. Folded into GPT-4 Turbo and GPT-4o, but still reachable via legacy API identifiers.',
    current_version: 'gpt-4-vision-preview',
    pricing_input_per_1m: 10,
    pricing_output_per_1m: 30,
    context_window: 128000,
    release_date: '2023-09-25',
  },
  {
    name: 'Claude 3.5 Sonnet (Vision)',
    slug: 'claude-3-5-sonnet-vision',
    maker: 'Anthropic',
    category: 'multimodal',
    description:
      'The vision-capable Claude 3.5 Sonnet, able to read charts, diagrams, and screenshots. Formed the base of the first Claude computer-use feature in late 2024.',
    current_version: 'claude-3-5-sonnet-20241022',
    pricing_input_per_1m: 3,
    pricing_output_per_1m: 15,
    context_window: 200000,
    release_date: '2024-06-20',
  },
]
